- name: Install Tomcat and Nexus
  hosts: all
  become: yes
  tasks:
    - name: Install Java
      apt:
        name: openjdk-17-jdk
        state: present

    - name: Install Tomcat
      when: "'tomcat_server' in group_names"
      block:
        - name: Download Tomcat
          get_url:
            url: https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.99/bin/apache-tomcat-9.0.99.tar.gz
            dest: /opt/tomcat.tar.gz

        - name: Extract Tomcat
          unarchive:
            src: /opt/tomcat.tar.gz
            dest: /opt
            remote_src: yes

    - name: Install Nexus
      when: "'artifact_server' in group_names"
      block:
        - name: Download Nexus
          get_url:
            url: https://download.sonatype.com/nexus/3/nexus-unix-x86-64-3.78.2-04.tar.gz
            dest: /opt/nexus.tar.gz

        - name: Extract Nexus
          unarchive:
            src: /opt/nexus.tar.gz
            dest: /opt
            remote_src: yes
