# Check if Java is installed
- name: Check if Java is installed
  when: "'artifact_server' in group_names"
  command: java -version
  register: java_version
  ignore_errors: yes

# Install Java if not installed
- name: Install Java (only on artifact_server if not installed)
  when: "'artifact_server' in group_names and java_version.failed"
  apt:
    name: openjdk-17-jdk
    state: present
    
# Check if Nexus is installed
- name: Check if Nexus is installed
  when: "'artifact_server' in group_names"
  stat:
    path: /opt/nexus
  register: nexus_stat

# Only install Nexus if it is not installed
- name: Install Nexus (if not installed)
  when: "'artifact_server' in group_names and not nexus_stat.stat.exists"
  block:
    - name: Download Nexus
      get_url:
        url: https://download.sonatype.com/nexus/3/nexus-unix-x86-64-3.78.2-04.tar.gz
        dest: /opt/nexus.tar.gz

    - name: Extract Nexus
      unarchive:
        src: /opt/nexus.tar.gz
        dest: /opt
        remote_src: yes

    - name: Rename Nexus directory
      command:
        cmd: mv /opt/nexus-3.78.2-04 /opt/nexus

    - name: Create nexus user and group
      user:
        name: nexus
        shell: /bin/bash
        password: "{{ 'nexus' | password_hash('sha512') }}"
        state: present

    - name: Set ownership of Nexus directory
      command:
        cmd: chown -R nexus:nexus /opt/nexus

    - name: Create systemd service file for Nexus
      copy:
        dest: /etc/systemd/system/nexus.service
        content: |
          [Unit]
          Description=Nexus Repository Manager
          After=network.target

          [Service]
          Type=forking
          ExecStart=/opt/nexus/bin/nexus start
          ExecStop=/opt/nexus/bin/nexus stop
          User=nexus
          Group=nexus
          UMask=0007
          RestartSec=10
          Restart=always
          LimitNOFILE=4096

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd and start Nexus service
      systemd:
        name: nexus
        state: started
        enabled: yes

# If Nexus is already installed, just ensure it's running
- name: Ensure Nexus service is running (if Nexus was already installed)
  when: "'artifact_server' in group_names and nexus_stat.stat.exists"
  systemd:
    name: nexus
    state: started
    enabled: yes
