- name: Install Java (only on tomcat_server)
  when: "'tomcat_server' in group_names"
  apt:
    name: openjdk-17-jdk
    state: present
    
- name: Download Tomcat
  when: "'tomcat_server' in group_names"
  get_url:
    url: https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.99/bin/apache-tomcat-9.0.99.tar.gz
    dest: /opt/tomcat.tar.gz

- name: Extract Tomcat
  when: "'tomcat_server' in group_names"
  unarchive:
    src: /opt/tomcat.tar.gz
    dest: /opt
    remote_src: yes

- name: Rename Tomcat directory
  when: "'tomcat_server' in group_names"
  command:
    cmd: mv /opt/apache-tomcat-9.0.99 /opt/tomcat

- name: Set ownership of Tomcat directory
  when: "'tomcat_server' in group_names"
  command:
    cmd: chown -R ubuntu:ubuntu /opt/tomcat

- name: Modify server.xml to change Connector port
  when: "'tomcat_server' in group_names"
  lineinfile:
    path: /opt/tomcat/conf/server.xml
    regexp: '(<Connector port=")(\d+)(" protocol="HTTP/1.1")'
    line: '<Connector port="8888" protocol="HTTP/1.1" connectionTimeout="20000" redirectPort="8443" />'

- name: Modify context.xml to update RemoteAddrValve
  when: "'tomcat_server' in group_names"
  lineinfile:
    path: /opt/tomcat/conf/context.xml
    regexp: '(<Valve className="org.apache.catalina.valves.RemoteAddrValve" allow="127\.\d+\.\d+\.\d+|::1|0:0:0:0:0:0:0:1" />)'
    line: '<Valve className="org.apache.catalina.valves.RemoteAddrValve" allow=".*" />'

- name: Modify tomcat-users.xml to add roles and user
  when: "'tomcat_server' in group_names"
  blockinfile:
    path: /opt/tomcat/conf/tomcat-users.xml
    marker: "<!-- BEGIN TOMCAT USERS -->"
    block: |
      <tomcat-users>
          <role rolename="manager-gui"/>
          <role rolename="admin-gui"/>
          <role rolename="manager-script"/>
          <user username="admin" password="admin123" roles="manager-gui,admin-gui,manager-script"/>
      </tomcat-users>

- name: Copy WAR file to Tomcat's webapps directory
  when: "'tomcat_server' in group_names"
  copy:
    src: ~/workspace/SpringBoot-CICD/target/*.war
    dest: /opt/tomcat/webapps/

- name: Create systemd service file for Tomcat
  when: "'tomcat_server' in group_names"
  copy:
    dest: /etc/systemd/system/tomcat.service
    content: |
      [Unit]
      Description=Tomcat 9 servlet container
      After=network.target

      [Service]
      Type=forking
      ExecStart=/opt/tomcat/bin/startup.sh
      ExecStop=/opt/tomcat/bin/shutdown.sh
      User=root
      Group=root
      UMask=0007
      RestartSec=10
      Restart=always
      LimitNOFILE=4096

      [Install]
      WantedBy=multi-user.target

- name: Reload systemd and start Tomcat service
  when: "'tomcat_server' in group_names"
  systemd:
    name: tomcat
    state: started
    enabled: yes
