- name: Download Tomcat
  get_url:
    url: https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.99/bin/apache-tomcat-9.0.99.tar.gz
    dest: /opt/tomcat.tar.gz

- name: Extract Tomcat
  unarchive:
    src: /opt/tomcat.tar.gz
    dest: /opt
    remote_src: yes

- name: Rename Tomcat directory
  command:
    cmd: mv /opt/apache-tomcat-9.0.99 /opt/tomcat

- name: Set ownership of Tomcat directory
  command:
    cmd: chown -R ubuntu:ubuntu /opt/tomcat

- name: Create systemd service file for Tomcat
  copy:
    dest: /etc/systemd/system/tomcat.service
    content: |
      [Unit]
      Description=Tomcat 9 servlet container
      After=network.target

      [Service]
      Type=forking
      ExecStart=/opt/tomcat/bin/startup.sh
      ExecStop=/opt/tomcat/bin/shutdown.sh
      User=root
      Group=root
      UMask=0007
      RestartSec=10
      Restart=always
      LimitNOFILE=4096

      [Install]
      WantedBy=multi-user.target

- name: Reload systemd and start Tomcat service
  systemd:
    name: tomcat
    state: started
    enabled: yes
